apiVersion: v1
kind: PersistentVolume
metadata:
   name: mypv
   labels:
     type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
     volumeID: vol-0bd4c30c073c0b50f
     fsType: ext4
  storageClassName: ebs-disk